version: '3'

services:
  db:
    image: tienpvse/postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: crm
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - networks
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql

networks:
  networks:

volumes:
  db_data:
