export const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['personal'],
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park',
    number: '0712388912',
    tags: ['unknown'],
  },
  {
    key: '3',
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
    number: '0712388912',
    tags: ['company'],
  },
  {
    key: '4',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['personal'],
  },
  {
    key: '5',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['company'],
  },
  {
    key: '6',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['personal'],
  },
  {
    key: '7',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['company'],
  },
  {
    key: '8',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['unknown'],
  },
  {
    key: '9',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['personal'],
  },
  {
    key: '10',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['unknown'],
  },
  {
    key: '11',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    number: '0712388912',
    tags: ['company'],
  },
];
