apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgAdmin.service.name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.pgAdmin.service.port }}
    targetPort: {{ .Values.pgAdmin.service.port }}
    protocol: TCP
  selector:
    app: {{ .Values.pgAdmin.deployment.name }} 