export enum controllers {
  TEST = 'test',
  AUTH = 'auth',
  ACCOUNT = 'account',
  PIPELINE = 'pipeline',
  PIPELINE_COLUMN = 'pipeline-column',
  PIPELINE_ITEM = 'pipeline-item',
  CONTACT = 'contact',
  CONTACT_FORM = 'contactForm',
  CONTACT_FORM_FIELD = 'contact-form-field',
  MAILER = 'mailer',
  EMAIL_TEMPLATE = 'email-template',
  PRODUCT = 'product',
  HISTORY = 'history',
  SCHEDULE = 'schedule',
  TEAM = 'team',
}
