export enum controllers {
  TEST = 'test',
  AUTH = 'auth',
  ACCOUNT = 'account',
  PIPELINE = 'pipeline',
  PIPELINE_COLUMN = 'pipeline-column',
  PIPELINE_ITEM = 'pipeline-item',
  CONTACT = 'contact',
  CONTACT_FORM = 'contactForm',
  CONTACT_FORM_FIELD = 'contact-form-field',
  MAILER = 'mailer',
  EMAIL_TEMPLATE = 'email-template',
  NOTIFICATION = 'notification',
  PRODUCT = 'product',
  HISTORY = 'history',
  SCHEDULE = 'schedule',
  SESSION = 'session',
  TEAM = 'team',
  OPPORTUNITY_HISTORY = 'opportunity-history',
  OPPORTUNITY_REVENUE = 'opportunity-revenue',
  COMPANY = 'company',
  COURSE = 'course',
  INBOX = 'inbox',
  EMAIL = 'email',
  CITY = 'city',
  REASON = 'reason',
  TAG = 'tag',
}
