name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: stop the server
        run: |
          cd ~/actions-runner/_work/monorepo/monorepo/crm
          docker-compose down
          docker rmi -f crm
      - name: build the front-end production
        run: |
          cd ~/actions-runner/_work/monorepo/monorepo/client
          npm i
          npm run build
      - name: start the server
        run: |
          cd ~/actions-runner/_work/monorepo/monorepo/crm
          docker-compose up -d
